### ISSUE TITLE
More sample data to train model from scratch

### ISSUE THREAD

**Issue by tmquan** [js3611/Deep-MRI-Reconstruction#2]
Hi @js3611 , 

In the paper, you mentioned that "our data is consisting of 10 fully sampled short-axis cardiac cine MR scans. Each scan contains a single slice SSFP acquisition with 30 temporal frames with a 320 × 320
mm field of view and 10 mm slice thickness". 

But in the data repo, there are only 256x256 x 30 frames. 
I assume that this is one of 10 scans. Is it possible to release the rest of 9 scans so that I can train your model from scratch? 

Best,

**Comment by js3611** [comment]
Hi @tmquan,

Indeed the sample data uploaded is 1/10 used in the paper. Unfortunately I do not have the permission to share the entire dataset online. Thank you for your understanding.

Best,
